/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const Question = IDL.Record({
  'id' : IDL.Nat,
  'questionText' : IDL.Text,
  'required' : IDL.Bool,
  'fieldType' : IDL.Text,
});
export const GameTile = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'isOpen' : IDL.Bool,
  'platform' : IDL.Text,
  'questions' : IDL.Vec(Question),
  'bannerUrl' : IDL.Text,
  'entryFee' : IDL.Nat,
});
export const Answer = IDL.Record({
  'answer' : IDL.Text,
  'questionId' : IDL.Nat,
});
export const Time = IDL.Int;
export const Registration = IDL.Record({
  'id' : IDL.Nat,
  'uid' : IDL.Text,
  'inGameName' : IDL.Text,
  'paymentStatus' : IDL.Text,
  'owner' : IDL.Principal,
  'answers' : IDL.Vec(Answer),
  'createdAt' : Time,
  'gameId' : IDL.Nat,
  'playerName' : IDL.Text,
  'transactionId' : IDL.Text,
  'paymentScreenshotUrl' : IDL.Opt(IDL.Text),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'checkTransactionId' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'createGame' : IDL.Func([GameTile], [IDL.Nat], []),
  'createQuestion' : IDL.Func([Question], [IDL.Nat], []),
  'deleteGame' : IDL.Func([IDL.Nat], [], []),
  'deleteQuestion' : IDL.Func([IDL.Nat], [], []),
  'getCallerRegistrations' : IDL.Func([], [IDL.Vec(Registration)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getGame' : IDL.Func([IDL.Nat], [GameTile], ['query']),
  'getGameRegistrations' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(Registration)],
      ['query'],
    ),
  'getQuestion' : IDL.Func([IDL.Nat], [Question], ['query']),
  'getQuestions' : IDL.Func([], [IDL.Vec(Question)], ['query']),
  'getRegistration' : IDL.Func([IDL.Nat], [Registration], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'listAllGames' : IDL.Func([], [IDL.Vec(GameTile)], ['query']),
      'listOpenGames' : IDL.Func([], [IDL.Vec(GameTile)], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'submitRegistration' : IDL.Func([Registration], [IDL.Nat], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateGame' : IDL.Func([GameTile], [], []),
  'updatePaymentStatus' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'updateQuestion' : IDL.Func([Question], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const Question = IDL.Record({
    'id' : IDL.Nat,
    'questionText' : IDL.Text,
    'required' : IDL.Bool,
    'fieldType' : IDL.Text,
  });
  const GameTile = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'isOpen' : IDL.Bool,
    'platform' : IDL.Text,
    'questions' : IDL.Vec(Question),
    'bannerUrl' : IDL.Text,
    'entryFee' : IDL.Nat,
  });
  const Answer = IDL.Record({ 'answer' : IDL.Text, 'questionId' : IDL.Nat });
  const Time = IDL.Int;
  const Registration = IDL.Record({
    'id' : IDL.Nat,
    'uid' : IDL.Text,
    'inGameName' : IDL.Text,
    'paymentStatus' : IDL.Text,
    'owner' : IDL.Principal,
    'answers' : IDL.Vec(Answer),
    'createdAt' : Time,
    'gameId' : IDL.Nat,
    'playerName' : IDL.Text,
  });
  const Sponsor = IDL.Record({ 'id' : IDL.Nat, 'name' : IDL.Text, 'mediaUrl' : IDL.Text, 'mediaType' : IDL.Text });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'checkTransactionId' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'createGame' : IDL.Func([GameTile], [IDL.Nat], []),
    'createQuestion' : IDL.Func([Question], [IDL.Nat], []),
    'deleteGame' : IDL.Func([IDL.Nat], [], []),
    'deleteQuestion' : IDL.Func([IDL.Nat], [], []),
    'getCallerRegistrations' : IDL.Func([], [IDL.Vec(Registration)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getGame' : IDL.Func([IDL.Nat], [GameTile], ['query']),
    'getGameRegistrations' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Registration)],
        ['query'],
      ),
    'getQuestion' : IDL.Func([IDL.Nat], [Question], ['query']),
    'getQuestions' : IDL.Func([], [IDL.Vec(Question)], ['query']),
    'getRegistration' : IDL.Func([IDL.Nat], [Registration], ['query']),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'listAllGames' : IDL.Func([], [IDL.Vec(GameTile)], ['query']),
      'listOpenGames' : IDL.Func([], [IDL.Vec(GameTile)], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'submitRegistration' : IDL.Func([Registration], [IDL.Nat], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateGame' : IDL.Func([GameTile], [], []),
    'updatePaymentStatus' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'addSponsor' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
    'deleteSponsor' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getSponsors' : IDL.Func([], [IDL.Vec(Sponsor)], ['query']),
    'updateQuestion' : IDL.Func([Question], [], []),
  });
};

export const init = ({ IDL }) => { return []; };