/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Answer { 'answer' : string, 'questionId' : bigint }
export interface GameTile {
  'id' : bigint,
  'title' : string,
  'description' : string,
  'isOpen' : boolean,
  'platform' : string,
  'questions' : Array<Question>,
  'bannerUrl' : string,
  'entryFee' : bigint,
}
export interface Question {
  'id' : bigint,
  'questionText' : string,
  'required' : boolean,
  'fieldType' : string,
}
export interface Registration {
  'id' : bigint,
  'uid' : string,
  'inGameName' : string,
  'paymentStatus' : string,
  'owner' : Principal,
  'answers' : Array<Answer>,
  'createdAt' : Time,
  'gameId' : bigint,
  'playerName' : string,
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export type Time = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createGame' : ActorMethod<[GameTile], bigint>,
  'createQuestion' : ActorMethod<[Question], bigint>,
  'deleteGame' : ActorMethod<[bigint], undefined>,
  'deleteQuestion' : ActorMethod<[bigint], undefined>,
  'getCallerRegistrations' : ActorMethod<[], Array<Registration>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getGame' : ActorMethod<[bigint], GameTile>,
  'getGameRegistrations' : ActorMethod<[bigint], Array<Registration>>,
  'getQuestion' : ActorMethod<[bigint], Question>,
  'getQuestions' : ActorMethod<[], Array<Question>>,
  'getRegistration' : ActorMethod<[bigint], Registration>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'listAllGames' : ActorMethod<[], Array<GameTile>>,
  'listOpenGames' : ActorMethod<[], Array<GameTile>>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'submitRegistration' : ActorMethod<[Registration], bigint>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateGame' : ActorMethod<[GameTile], undefined>,
  'updatePaymentStatus' : ActorMethod<[bigint, string], undefined>,
  'updateQuestion' : ActorMethod<[Question], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];